disabled_rules:
  - multiple_closures_with_trailing_closure
  - non_optional_string_data_conversion
  - todo
line_length:
  ignores_comments: true
excluded:
  - DerivedData
identifier_name:
  excluded: [x, y, up, id]
type_body_length:
  warning: 350
  error: 800
